### ISSUE TITLE
resource not found

### ISSUE THREAD

**Issue by LtRobX** [TrevorBarns/luxart-vehicle-control#17]
Latest release from 5 days ago doesn't show up ingame. Console says couldn't find resource dont know why. Previous release worked fine

**Comment by TrevorBarns** [comment]
Please follow these instructions here: [Wiki - Installation](https://github.com/TrevorBarns/luxart-vehicle-control/wiki/Installation#resource-installation). This is most likely caused by user error. Verify your resource name. Try restarting the server.

**Comment by LtRobX** [comment]
> Please follow these instructions here: [Wiki - Installation](https://github.com/TrevorBarns/luxart-vehicle-control/wiki/Installation#resource-installation). This is most likely caused by user error. Verify your resource name. Try restarting the server.

I followed the instructions to no avail, still not working, gonna revert to the previous version

**Comment by TrevorBarns** [comment]
In order to further investigate this, I will need additional information since you are the only report right now. 
Can you please provide:
1. A description or screenshot of both the `lux_vehcontrol_full` and `RageUI` folder path? 
    e.g `/resources/<some folders>/lux_vehcontrol`
          `/resources/RageUI`

2. A screenshot of the specific error that your server console is reporting?  
3. A screenshot or copy of the `ensure` or `start` line in your server.cfg?
    e.g. `ensure lux_vehcontrol`
